#!/usr/bin/env python3
"""
Zero-Dependency Data-Contract JSON Schema Validator
--------------------------------------------------
Validates target JSON files generated by subagents against their formal JSON schemas.
Runs natively on any standard Python 3 runtime without pip dependencies.

Usage:
    python3 validate_schemas.py <data_file_path> <schema_file_path>
"""

import sys
import os
import json

class NativeSchemaValidator:
    def __init__(self):
        self.errors = []

    def validate(self, data, schema, path=""):
        if not isinstance(schema, dict):
            return

        # 1. Check required fields
        if "required" in schema and isinstance(schema["required"], list):
            # If data is not a dict, the type check will catch it, but prevent crash here
            if isinstance(data, dict):
                for field in schema["required"]:
                    if field not in data:
                        self.errors.append(f"Missing required field: '{path + '.' if path else ''}{field}'")

        # 2. Check types and recurse
        if "type" in schema:
            expected_type = schema["type"]
            if expected_type == "object":
                if not isinstance(data, dict):
                    self.errors.append(f"Field '{path or 'root'}' is expected to be an object, but got {type(data).__name__}")
                else:
                    properties = schema.get("properties", {})
                    # Validate existing properties
                    for key, val in data.items():
                        if key in properties:
                            self.validate(val, properties[key], f"{path}.{key}" if path else key)
                    
                    additional_properties = schema.get("additionalProperties")
                    if additional_properties is False:
                        for key in data:
                            if key not in properties:
                                self.errors.append(f"Property '{path + '.' if path else ''}{key}' is not allowed by the schema")
                    elif isinstance(additional_properties, dict):
                        for key, val in data.items():
                            if key not in properties:
                                self.validate(val, additional_properties, f"{path}.{key}" if path else key)
            elif expected_type == "array":
                if not isinstance(data, list):
                    self.errors.append(f"Field '{path or 'root'}' is expected to be an array, but got {type(data).__name__}")
                else:
                    items_schema = schema.get("items")
                    if items_schema:
                        for idx, item in enumerate(data):
                            self.validate(item, items_schema, f"{path or 'root'}[{idx}]")
            elif expected_type == "string":
                if not isinstance(data, str):
                    self.errors.append(f"Field '{path or 'root'}' is expected to be a string, but got {type(data).__name__}")
            elif expected_type == "integer":
                # Note: bool is a subclass of int in Python, so check explicitly
                if not isinstance(data, int) or isinstance(data, bool):
                    self.errors.append(f"Field '{path or 'root'}' is expected to be an integer, but got {type(data).__name__}")
            elif expected_type == "number":
                if not isinstance(data, (int, float)) or isinstance(data, bool):
                    self.errors.append(f"Field '{path or 'root'}' is expected to be a number, but got {type(data).__name__}")
            elif expected_type == "boolean":
                if not isinstance(data, bool):
                    self.errors.append(f"Field '{path or 'root'}' is expected to be a boolean, but got {type(data).__name__}")

        # 3. Check enum constraints
        if "enum" in schema and isinstance(schema["enum"], list):
            if data not in schema["enum"]:
                self.errors.append(f"Field '{path or 'root'}' must be one of {schema['enum']}, but got '{data}'")

def main():
    if len(sys.argv) < 3:
        print("[-] Usage: python3 validate_schemas.py <data_file_path> <schema_file_path>")
        sys.exit(2)

    data_path = sys.argv[1]
    schema_path = sys.argv[2]

    # Establish validation directories
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    report_dir = os.path.join(base_dir, "output", "artifacts")
    os.makedirs(report_dir, exist_ok=True)
    report_file = os.path.join(report_dir, "validation-report.json")

    print(f"[*] Validating Contract: {os.path.basename(data_path)} against {os.path.basename(schema_path)}")

    # 1. Load Data
    if not os.path.exists(data_path):
        err_msg = f"Data file not found: {data_path}"
        print(f"[!] {err_msg}")
        # Write direct report
        with open(report_file, 'w') as f:
            json.dump({"status": "fail", "errors": [err_msg]}, f, indent=2)
        sys.exit(1)

    try:
        with open(data_path, 'r') as f:
            data = json.load(f)
    except Exception as e:
        err_msg = f"Failed to parse data JSON: {str(e)}"
        print(f"[!] {err_msg}")
        with open(report_file, 'w') as f:
            json.dump({"status": "fail", "errors": [err_msg]}, f, indent=2)
        sys.exit(1)

    # 2. Load Schema
    if not os.path.exists(schema_path):
        err_msg = f"Schema file not found: {schema_path}"
        print(f"[!] {err_msg}")
        with open(report_file, 'w') as f:
            json.dump({"status": "fail", "errors": [err_msg]}, f, indent=2)
        sys.exit(1)

    try:
        with open(schema_path, 'r') as f:
            schema = json.load(f)
    except Exception as e:
        err_msg = f"Failed to parse schema JSON: {str(e)}"
        print(f"[!] {err_msg}")
        with open(report_file, 'w') as f:
            json.dump({"status": "fail", "errors": [err_msg]}, f, indent=2)
        sys.exit(1)

    # 3. Perform Validation
    validator = NativeSchemaValidator()
    validator.validate(data, schema)

    report_data = {}
    if validator.errors:
        print(f"[❌] Validation failed with {len(validator.errors)} error(s):")
        for err in validator.errors[:10]:
            print(f"  - {err}")
        if len(validator.errors) > 10:
            print(f"  - ... and {len(validator.errors) - 10} more.")
        
        report_data = {
            "status": "fail",
            "data_file": data_path,
            "schema_file": schema_path,
            "errors": validator.errors
        }
        status_code = 1
    else:
        print("[✅] Contract validation passed successfully!")
        report_data = {
            "status": "pass",
            "data_file": data_path,
            "schema_file": schema_path,
            "errors": []
        }
        status_code = 0

    # Write report
    with open(report_file, 'w') as f:
        json.dump(report_data, f, indent=2)

    sys.exit(status_code)

if __name__ == "__main__":
    main()
